InforQui_17933/InforQui_17933/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using InforQui_17933.Models;

namespace InforQui_17933.Controllers
{
    public class ClientesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //***********************************************************************************************************************
        //      O ação para Index o produto para a tabela
        //***********************************************************************************************************************

        // GET: Clientes
        public ActionResult Index(string Procurar, int? pagina)
        {
            var produtos = from s in db.Produtos
                           select s;
            if (!String.IsNullOrEmpty(Procurar))
            {
                produtos = produtos.Where(s => s.Nome.Contains(Procurar));
            }


            //#########################################################
            //#####Fazer a paginação dos produtos######################

            //atribui para a variavel tamanhoPagina o valor inteiro '5'
            int tamanhoPagina = 5;
            //atribuir para a variavel numeroPagina o numero 'um' se for o parametro da 'pagina' não esta definido
            int numeroPagina = pagina ?? 1;     // o número da pagina for nulo, vamos inserir um
            
            //retorna para o view uma lista de paginas da tabela 'Produtos' que vai ordenar segundo o nome do 'produto' 
            //com 'cinco' produtos e listar começa com 'um'
            return View(db.Produtos.OrderBy(p => p.Nome).ToPagedList(numeroPagina, tamanhoPagina));
        }

        //***********************************************************************************************************************
        //      O ação para Index o produto para a tabela
        //***********************************************************************************************************************

        // GET: Clientes/Detalhes/5
        public ActionResult Detalhes(int? id)
        {
            //Se o 'ID' do produto igual a nulo ou quer dizer não colocado
            if (id == null)
            {
                // gera um erro que se disse: "Não coloca o 'ID' do produto"
                ModelState.AddModelError("", "Por favor coloca o 'ID' do produto!");
            }
            // Na tabela 'Produtos' vai gerar um novo objeto 'produto' que vai receber o base de dados 'ApplicationDbContext'
            // com o 'ID' do produto pretendido 
            Produtos produto = db.Produtos.Find(id);
            //Se o produto pretendido não existe na tabela
            if (produto == null)
            {
                //vai retornar um 'erro' que se disse: "o produto não existe na tabela"
                ModelState.AddModelError("", "Não existe o produto na tabela!");
            }
            //retornar para o view da tabela 'Produto'
            return View(produto);
        }


        public ActionResult AddCart()
        {
            return View();
        }
    }
}

InforQui_17933/InforQui_17933/Controllers/RolesAdminController.cs
using InforQui_17933.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;

namespace InforQui_17933.Controllers
{
    [Authorize(Roles = "Administrador")]

    //Criar uma classe RolesAdmin que herda do classe controller
    public class RolesAdminController : Controller
    {
        //Construtor da classe 'RolesAdmin' sem argumentos
        public RolesAdminController()
        {
        }

        //Construtor da classe RolesAdmin com argumento: 'objeto userManager da classe ApplicationUserManager e
        //o objeto roleManager da classe ApplicationRoleManager'
        public RolesAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        //Criar os objetos privados que instanciar com as classe ApplicationUserManager
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            //Criar o metodo get
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            //criar o metodo set
            set
            {
                _userManager = value;
            }
        }

        //Criar os objetos privados que instanciar com as classe ApplicationRoleManager
        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            //Criar o metodo get
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            //criar o metodo set com tipo 'privado'
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        //
        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Buscar a lista dos utilizadores neste Role ou seja
            //criar o novo variavel para referenciar com a lista dos utilizadores
            var users = new List<ApplicationUser>();

            //Vai listar para cada utilizador que está instanciado com a classe UserManager
            foreach (var user in UserManager.Users.ToList())
            {
                //Se o utilizador está na RoleAsync
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    //então adicionar para a lista dos Roles
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            //retornar uma lista dos RolesAsync
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            //Se o modelo está valido
            if (ModelState.IsValid)
            {
                var role = new IdentityRole(roleViewModel.Name);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

InforQui_17933/InforQui_17933/Controllers/UserAdminController.cs
using InforQui_17933.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace InforQui_17933.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(Registo userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

InforQui_17933/InforQui_17933/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="~/Content/Imagens/InforQui1.png">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <nav class="navbar-inner" style="background-color:#00ffff;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        <li style="border:2px solid #ffffff;">
                            <button class="btn btn-info">
                                <img src="~/Content/Imagens/Home.png" width="40" height="40" />
                                @Html.ActionLink("Inicio", "Index", "Clientes")
                            </button>
                        </li>

                        <li style="border:2px solid #ffffff">
                            <button class="btn btn-info">
                                <img src="~/Content/Imagens/sobre.png" width="40" height="40" />
                                @Html.ActionLink("Sobre", "Sobre", "Home")
                            </button>
                        </li>

                        <li style="border:2px solid #ffffff">
                            <button class="btn btn-info">
                                <img src="~/Content/Imagens/contact.png" width="40" height="40" />
                                @Html.ActionLink("Contactos", "Contactos", "Home")
                            </button>
                        </li>

                        <li style="border:2px solid #ffffff">
                            <button class="btn btn-info">
                                <img src="~/Content/Imagens/utilizador.png" width="40" height="40" />
                                @Html.ActionLink("Utilizadores", "Utilizador", "Home")
                            </button>
                        </li>

                        @* Só permitir para o role 'Funcionario' *@
                        @if (User.IsInRole("Funcionario"))
                        {
                            <li style="border:2px solid #ffffff">
                                <button class="btn btn-info">
                                    <img src="~/Content/Imagens/Funcionaro.png" width="40" height="40" />
                                    @Html.ActionLink("Funcionarios", "Index", "Funcionarios")
                                </button>
                            </li>
                        }

                        @* Permite mostrar estes dois link ou navegador para os utilizadores autenticados e o tipo role 'Administrador' *@
                        @if (Request.IsAuthenticated && User.IsInRole("Administrador"))
                        {
                            <li style="border:2px solid #ffffff">
                                <button class="btn btn-info">
                                    <img src="~/Content/ImagensUtilizadores/Mariano_Freitas.png" width="40" height="40" />
                                    @Html.ActionLink("Roles Admin", "Index", "RolesAdmin")
                                </button>
                            </li>
                            <li style="border:2px solid #ffffff">
                                <button class="btn btn-info">
                                    <img src="~/Content/ImagensUtilizadores/Manuel_Pinto.png" width="40" height="40" />
                                    @Html.ActionLink("Utilizadores Autenticado", "Index", "UsersAdmin")
                                </button>
                            </li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </nav>
    </div>
    @* O render body ou seja o corpo do browser ou aplicação *@
    <div class="container body-content">
        @RenderBody()
    </div>

    <br /><br />
    <div style="top:85%; position:relative">
        <hr style="background-color:#00ffff; height:50px; width:1250px; " />

        <div style="left:10%; position:absolute">
            <p><b>&copy; @DateTime.Now.Year - InforQui coorporation</b></p>
        </div>
        <div style="left:40%; position:absolute; ">
            <div style="font-family:Algerian">Siga-nos nas redes sociais</div>
        </div><br />
        <div style="left:40%; position:absolute;">
            <a href="https://www.facebook.com/InforQui-1924713121076966/" target="_blank"><img src="~/Content/Imagens/face.png" style="height:30px; width:30px;" /></a>
        </div>
        <div style="left:44%; position:absolute;">
            <a href="https://www.youtube.com/channel/UCYJ4Xd6Nsq1jeC2MFkEBnNQ" target="_blank"><img src="~/Content/Imagens/YouTube.png" style="height:30px; width:40px;" /></a>
        </div>
        <div style="left:48%; position:absolute; ">
            <a href="https://www.instagram.com/inforqui6049/" target="_blank"><img src="~/Content/Imagens/instagram.png" style="height:30px; width:30px;" /></a>
        </div>
        <div style="left:60%; position:absolute;">
            <img src="~/Content/Imagens/InforQui1.png" style="height:30px; width:30px;" title="Messenger InforQui" />
        </div>
    </div>
    <br /><br />


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>