InforQui_17933/InforQui_17933/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using InforQui_17933.Models;

namespace InforQui_17933.Controllers
{
    [Authorize(Roles = "Funcionario")]
    public class FuncionariosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Funcionarios/Index
        public ActionResult Index(int? pagina)
        {
            
            //#########################################################
            //#####Fazer a paginação dos produtos######################
            int tamanhoPagina = 5;
            int numeroPagina = pagina ?? 1;     // o número da pagina for nulo, vamos inserir um

            //vai retornar para o 'VIEW', a lista da tabela 'Produtos' na base de dados 'ApplicationDbContext'
            //e vai ordenar por o 'Nome' do produto
            return View(db.Produtos.OrderBy(p => p.Nome).ToPagedList(numeroPagina, tamanhoPagina));
        }

        // GET: Funcionarios/Detalhes/5
        public ActionResult Detalhes(int? id)
        {
            // Se o 'id' do produto igual a nulo
            if (id == null)
            {
                // gera um erro que se disse: "Não coloca o 'ID' do produto"
                ModelState.AddModelError("","Por favor coloca o 'ID' do produto!");
            }
            //Se não, vai encontrar ou criar um novo 'id' para a tabela 'Produto'
            Produtos produtos = db.Produtos.Find(id);
            // Se este 'id' novo que foi criado, for igual a nulo
            if (produtos == null)
            {
                //vai retornar um 'erro' que se disse: "o produto não existe na tabela"
                ModelState.AddModelError("","Não existe o produto na tabela!");
            }
            //Se não, vai retornar para o 'View' os produto na tabela
            return View(produtos);
        }


        //***********************************************************************************************************************
        //      O ação para Adicionar o produto para a tabela
        //***********************************************************************************************************************

        // GET: funcionarios/Adicionar
        public ActionResult Adicionar()
        {
            // retorna para o 'VIEW' 
            return View();
        }

        // POST: Funcionarios/Adicionar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar([Bind(Include = "ProdutosID,Nome,Descricao,Preco,Imagem,Tipo")] Produtos produto, HttpPostedFileBase file) //HttpPostedFileBase é uma classe do sistema que permite os clientes fazer o upload dos ficheiros
        {

            //determinar o nº (ID) a atribuir a novo 'Produto'
            //criar a variavel que recebe o valor do novo 'produto'

            int novoID = 0;

            try
            {
                //##############################
                //determinar o novo ID

                //O novoID receber a tabela Produtos
                novoID = (from p in db.Produtos 
                          //Ordenar a tabela 'Produto' baseia-se no atributo 'ProdutoID' se forma descedente
                          orderby p.ProdutoID descending
                          //Listar a tabela 'Produtos' com o valor máximo do 'ProdutoID' + 1 
                          select p.ProdutoID).FirstOrDefault() + 1;
            }
            catch (System.Exception)
            {
                // a tabela de 'Produtos' está vazia
                // não sendo possivel devolver o MAX de uma tabela
                // por isso, vou atribuir 'manualmente' o valor do 'noovoID'
                novoID = 1;
            }

            //atribuir o 'novoID' ao objeto produto
            produto.ProdutoID = novoID;


            try
            {
                // Se o modelo ou classe 'Produtos' não tem erro
                if (ModelState.IsValid)
                {
                    // Se o ficheiro que estava upload não igual a nulo
                    if (file != null)
                    {
                        //Vai guardar este ficheiro no servidor baseada neste caminho
                        file.SaveAs(HttpContext.Server.MapPath("~/Content/Imagens/") + file.FileName);
                        //O atributo 'imagem' da tabela 'Produto' vai receber o ficheiro
                        produto.Imagem = file.FileName;
                    }
                    // vai adicionar para a tabela 'Produtos' e o BD 'InforQuiDB'
                    db.Produtos.Add(produto);
                    //vai guardar no BD 'InforQui'
                    db.SaveChanges();
                    //retornar para o 'Index' dos produto
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                // não consigo guardar as alterações 
                //No minimo, preciso de notificar o utilizador que o processo falhou
                ModelState.AddModelError("", "O valor do ID introduzindo é erro!");
                //notificar o 'administrador/programador' que ocorreu este erro
                //fazer: 1º enviar email ao programador a informar da ocorrência do erro
                // 2º ter uma tabela, na BD onde são reportados os erros: 
                //  -data
                //  -método
                //  -controller
                //  -detalhes do erro
            }
            //Retornar para o 'View' dos Produtos
            return View(produto);
        }
        //******************************fim do ação ****************************************************************************


        //***********************************************************************************************************************
        //      O ação para Atualizar o produto para a tabela
        //***********************************************************************************************************************

        // GET: Funcionarios/Atualizar/5
        public ActionResult Atualizar(int? id)
        {
            // Se o 'id' igual a nulo
            if (id == null)
            {
                // gera um erro que se disse: "Não coloca o 'ID' do produto"
                ModelState.AddModelError("", "Por favor coloca o 'ID' do produto!");
            }
            //Se não, vai encontrar ou criar um novo 'id' para a tabela 'Produto'
            Produtos produtos = db.Produtos.Find(id);
            //Se a tabela 'Produtos' igual a nulo
            if (produtos == null)
            {
                //vai retornar um 'erro' que se disse: "o produto não existe na tabela"
                ModelState.AddModelError("", "Não existe o produto na tabela!");
            }
            //retorna para o 'View' os produto
            return View(produtos);
        }

        // POST: Funcionarios/Atualizar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Esta ActionResult vai ligar para os atributos da tabela 'Produtos'
        public ActionResult Atualizar([Bind(Include = "ProdutoID,Nome,Descricao,Preco,Tipo")] Produtos produto, HttpPostedFileBase file)
        {
            // Se o modelo ou classe 'Produtos' não tem erro
            if (ModelState.IsValid)
            {
                // Se o ficheiro que estava upload não igual a nulo
                if (file != null)
                {
                    //Vai guardar este ficheiro no servidor baseada neste caminho
                    file.SaveAs(HttpContext.Server.MapPath("~/Content/Imagens/") + file.FileName);
                    //O atributo 'imagem' da tabela 'Produto' vai receber o ficheiro
                    produto.Imagem = file.FileName;
                   // db.Entry(file).State = EntityState.Modified;
                }
                else
                {
                    // não se pretende trocar a imagem
                    //**********************************
                    // procurar os dados do produto q estão guardados na BD
                    //Produtos auxProduto = db.Produtos.Find(produto.ProdutoID);
                    // atribuir ao novo produto, o nome da imagem que está guardado na BD
                    produto.Imagem = db.Produtos.AsNoTracking().Where(p=>p.ProdutoID==produto.ProdutoID).FirstOrDefault().Imagem;
                }

                db.Entry(produto).State = EntityState.Modified;

                    try
                    {
                        //vai guardar no base de dados 'InforQui', se já não tem erro
                        db.SaveChanges();
                    }
                    catch (System.Exception)
                    {
                        //vai gerar o erro para informar ao utilizador
                        ModelState.AddModelError("","Não consegue atualizar o produto na tabela!");
                        return View(produto);
                    }
                //retornar e redirecionar o ação para o 'View' Index
                return RedirectToAction("Index");
            }
            //retorna para o 'View' da tabela 'Produtos'
            return View(produto);
        }
        //******************************fim do ação ****************************************************************************


        //***********************************************************************************************************************
        //      O ação para Remover o produto para a tabela
        //***********************************************************************************************************************

        // GET: Funcionarios/Remover/5
        public ActionResult Remover(int? id)
        {
            // Se o 'id' do produto igual a nulo
            if (id == null)
            {
                //vai retornar o erro do Http

InforQui_17933/InforQui_17933/Views/Funcionarios/Adicionar.cshtml
@model InforQui_17933.Models.Produtos

@{
    ViewBag.Title = "Adicionar os produtos";
}


@using (Html.BeginForm("Adicionar", "Funcionarios", null, FormMethod.Post,
                                          new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        <h4>Adicionar o novo produto</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="editor-field">
                    <input id="Imagem" title="Upload o imagem"
                           type="file" name="file" />
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label>@Html.RadioButtonFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })Instrumento</label><br />
                <labbel>@Html.RadioButtonFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })Material</labbel>
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />
        <div class="form-group">
            <div class="col-md-4">
                @Html.ActionLink("Voltar para a lista dos produtos", "Index")
                <input type="submit" value="Adicionar" class="btn btn-success" />
                @*<button class="btn-info glyphicon glyphicon-step-backward" style="height:40px;">*@
                   
                @*</button>*@
            </div>
        </div>
    </div>
}

<div>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InforQui_17933/InforQui_17933/Views/Funcionarios/Atualizar.cshtml
@model InforQui_17933.Models.Produtos

@{
    ViewBag.Title = "Atualizar";
}

<h2>Editar o produto</h2>


@using (Html.BeginForm("Atualizar", "Funcionarios", null, FormMethod.Post,
                                          new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProdutoID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="editor-field">
                    @{
                        <script>
                             //a função que vai mudar a imagem
                            function mudarImagem(input) {
                                //se o parametro input é o tipo 'file' e contenha o valor zero
                                    if (input.files && input.files[0])
                                    {
                                     //referençia uma variavel para o FileReader
                                    var reader = new FileReader();

                                    reader.onload = function(e) {
                                                                $('#imagem')
                                                                    .attr('src', e.target.result)
                                                                    .width(200)
                                                                    .height(200);
                                                                   };

                                    reader.readAsDataURL(input.files[0]);
                                    }
                            }
                        </script>
                    }
                    <img id="imagem" src="~/Content/Imagens/@Html.DisplayFor(model=>model.Imagem)" style="width:200px;height:200px" />
                    <input name="file" type='file' onchange="mudarImagem(this);" />
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="left:25%; top:94%; position:absolute">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" style="background-color:#00ff90;" />
            </div>
        </div>
    </div>
                        }

<br />
<div>
    <button class="btn-info">
        @Html.ActionLink("Regressar para a lista dos produtos", "Index")
    </button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InforQui_17933/InforQui_17933/Views/Funcionarios/Detalhes.cshtml
@model InforQui_17933.Models.Produtos

@{
    ViewBag.Title = "Detalhes dos produtos";
}

    <div style="float:left">

        <h4>
            @Html.DisplayFor(model => model.Nome)
        </h4>
        <hr />
        <table class="dl-horizontal" style="border:2px solid #808080;">
            <tr style="border:2px solid #808080;">
                <th style="border:2px solid #808080; text-align:center">
                    @Html.DisplayNameFor(model => model.Descricao)
                </th>
                <th style="border:2px solid #808080; text-align:center">
                    @Html.DisplayNameFor(model => model.Preco)
                </th>
                <th style="border:2px solid #808080; text-align:center">
                    @Html.DisplayNameFor(model => model.Tipo)
                </th>

            </tr>


            <tr style="border:2px solid #808080;">
                <td width="300px; text-align:center">
                    @Html.DisplayFor(model => model.Descricao)
                </td>

                <td style="border:2px solid #808080; text-align:center">
                    @Html.DisplayFor(model => model.Preco)
                </td>

                <td style="border:2px solid #808080; text-align:center">
                    @Html.DisplayFor(model => model.Tipo)
                </td>
            </tr>
        </table>
        <br />
        <p>
            <button class="btn-secondary glyphicon glyphicon-step-backward" style="height:40px;">
                @Html.ActionLink("Volta para a lista dos produtos", "Index")
            </button>
            <button class="btn-info glyphicon glyphicon-refresh" style="height:40px;">
                @Html.ActionLink("Atualizar", "Atualizar", new { id = Model.ProdutoID })
            </button>
            <button class="btn-danger glyphicon glyphicon-trash" style="height:40px;">
                @Html.ActionLink("Remover", "Remover", new { id = Model.ProdutoID })
            </button>
        </p>
    </div>
    <br /><br />

    <div style="float:right">
        <img src="~/Content/Imagens/@Html.DisplayFor(model =>model.Imagem)" style="height:200px;width:300px;" />
    </div>

<br />

InforQui_17933/InforQui_17933/Views/Funcionarios/Index.cshtml
@model PagedList.IPagedList<InforQui_17933.Models.Produtos>
    @using PagedList.Mvc;
    @{
        ViewBag.Title = "Index";
    }

    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    <br /><br />
    <button class="btn-info glyphicon glyphicon-plus" style="height:40px; font-size:14px;">
         @Html.ActionLink("Adicionar o produto", "Adicionar")
    </button>
<br /><br />
    <table>
        <tr style="border: 2px solid #00ffff;">
            <th style="border: 2px solid #00ffff; text-align:center">
                @Html.DisplayName("Nome do Produto")
            </th>
            <th style="border: 2px solid #00ffff; text-align:center">
                @Html.DisplayName("Descrição do produto")
            </th>
            <th style="border: 2px solid #00ffff; text-align:center">
                @Html.DisplayName("Imagem do produto")
            </th>
            <th style="border: 2px solid #00ffff; text-align:center">
                @Html.DisplayName("Preço do produto")
            </th>
            <th style="text-align:center">
                @Html.DisplayName("Tipo do produto")
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="border: 2px solid #00ffff; text-align:center">
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td  style="border: 2px solid #00ffff; text-align:center">
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td  style="border: 2px solid #00ffff;">
                    <a href='@Url.Action("Detalhes", "Funcionarios", new { id = item.ProdutoID })'>
                        <img src="~/Content/Imagens/@Html.DisplayFor(model =>item.Imagem)" style="height:200px;width:200px;" />
                    </a>
                </td>
                <td  style="border: 2px solid #00ffff;">
                    @Html.DisplayFor(modelItem => item.Preco)
                </td>
                <td  style="border: 2px solid #00ffff;">
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
            </tr>
        }

    </table>
    
<p>@Html.PagedListPager(Model, page => Url.Action("Index", new { pagina = page }))</p>
    

InforQui_17933/InforQui_17933/Views/Funcionarios/Remover.cshtml
@model InforQui_17933.Models.Produtos

@{
    ViewBag.Title = "Remover";
}


<h3>Quer remover mesmo o produto?</h3>
<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>

        <dd>
            <img src="~/Content/Imagens/@Html.DisplayFor(model =>model.Imagem)" style="height:200px;width:300px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Voltar para a lista", "Index") | 
            <input class="btn btn-default btn-danger glyphicon glyphicon-trash" style="height:40px;" type="submit" value="Remover" /> 
        </div>
    }
</div>